### ISSUE TITLE
New DOSDP Spec

### ISSUE THREAD

**Issue by shawntanzk** [Cellular-Semantics/whole_mouse_brain_ontology#1]
## Current State

rdfs:label "ADP-MPO Trp73 Glut brain glutamatergic neuron (Mmus)"^^xsd:string
skos:prefLabel "ADP-MPO Trp73 Glut"^^xsd:string
definition "A glutamatergic neuron of the Mus musculus brain. The reference data for this cell type is CS202211210_5328."^^xsd:string
has_exact_synonym "ADP-MPO Trp73 Glut"^^xsd:string
symbol "ADP-MPO Trp73 Glut MOp (Mouse)"^^xsd:string

EquivalentTo:
'native cell'
 and ('has exemplar data' value 'MouseBrain 02263-02281 - CS202211210_5328')

SubClassOf:
'glutamatergic neuron'
'has exemplar data' value 'MouseBrain 02263-02281 - CS202211210_5328'
'has soma location' some brain
'in taxon' some 'Mus musculus'
('soma located in' some 'Medial preoptic area')
 and ('soma located in' some 'Anterodorsal preoptic nucleus')

## Spec
```yaml
name:
   text: "%s %s (%s)"
   vars:
      - prefLabel
      - Gross_cell_type
      - Taxon_abbv

def:
  xrefs: Alias_citations
  multi_clause:
    sep: " "
    clauses:
      - text: 'A %s of the %s %s.'
        vars:
          - Gross_cell_type
          - Taxon
          - Brain_region
        sub_clauses:
          - sep: ' '
          - clauses:
              - text: 'These cells can be distinguished from other cells in the %s by their selective expression of %s.'
                vars:
                  - Brain_region
                  - Minimal_markers_cat
              - text: 'These cells also express %s.'
                vars:
                  - Allen_markers_cat
              - text: 'These cells have projection type %s.'
                vars:
                  - Projection_type
              - text: 'The soma of these cells can be found in %s.'
                vars:
                  - atlas_loc_cat
              - text: 'The reference data for this cell type is %s.'
                vars:
                  - Cluster_ID
```

#### Notes
New var:                  
 - atlas_loc_cat
(MBA label, comma sep, concatenate) 

```yaml
  - annotationProperty: symbol
    text: "%s (%s)"
    vars:
      - prefLabel
      - Species_abbv
```
(Removed 'Brain_region_abbv')
