### ISSUE TITLE
Update text def template system

### ISSUE THREAD

**Issue by dosumis** [Cellular-Semantics/whole_mouse_brain_ontology#15]
Current structure (with annotations)

```yaml
def:
  xrefs: Alias_citations
  multi_clause:
    sep: " "
    clauses:
      - text: 'A %s of the %s %s.'
        vars:
          - Gross_cell_type.   #  Use mapping to CL if there is one, otherwise just neuron?
          - Taxon # Keep
          - Brain_region. # Use gross brain region?
        sub_clauses:
          - sep: ' '
          - clauses:
              - text: 'These cells can be distinguished from other cells in the %s by their selective expression of %s.'
                vars:
                  - Brain_region
                  - Minimal_markers_cat
              - text: 'These cells also express %s.'
                vars:
                  - Allen_markers_cat
              - text: 'These cells have projection type %s.'  # Discard
                vars:
                  - Nomenclature_Projection
              - text: 'The soma of these cells can be found in the %s.' # Keep - using 
                vars:
                  - Atlas_loc_cat
              - text: 'The soma of these cells are also found in %s.'
                vars:
                  - Nomenclature_Layers # Drop
              - text: 'The reference data for this cell type is %s.' 
                vars:
                  - Cluster_ID # Keep 
```

Revised - draft:
```yaml
def:
  xrefs: Alias_citations
  multi_clause:
    sep: " "
    clauses:
      - text: 'A %s of the %s %s.'
        vars:
          - Gross_cell_type.   #  Use mapping to CL if there is one, otherwise just neuron or general non-neuronal type.
          - Taxon # Keep
          - Brain_region. # Use CCF_broad.freq  translated to MBA full names?
        sub_clauses:
          - sep: ' '
          - clauses:
              - text: 'These cells can be distinguished from others their selective expression of %s.'
                vars:
                  - Minimal_markers_cat # use markers.combo
              - text: 'The soma of these cells can be found in the %s.' 
                vars:
                  - Atlas_loc_cat # Use CCF_acronym.freq - translated to full region names.
              - text: 'The reference data for this cell type is %s.' 
                vars:
                  - Cluster_ID # Keep 
```
